const MAJOR = 'major';
const MINOR = 'minor';
const PATCH = 'patch';

const gitmojis = require("gitmojis")
console.log(gitmojis)
module.exports = [
  {breaking: true, release: MAJOR},
  {revert: true, release: PATCH},
  {
    // type: 'style',
    emoji: ':art:',
    // description: 'Improving structure / format of the code.',
    release: PATCH,
  },
  {
    // type: 'perf',
    emoji: ':zap:',
    // description: 'Improving performance.',
    release: PATCH,
  },
  {
    // type: 'prune',
    emoji: ':fire:',
    // description: 'Removing code or files.',
    release: PATCH,
  },
  {
    // type: 'fix',
    emoji: ':bug:',
    // description: 'Fixing a bug.',
    release: PATCH,
  },
  {
    // type: 'quickfix',
    emoji: ':ambulance:',
    // description: 'Critical hotfix.',
    release: MINOR,
  },
  {
    // type: 'feature',
    emoji: ':sparkles:',
    // description: 'Introducing new features.',
    release: MINOR,
  },
  {
    // type: 'docs',
    emoji: ':pencil:',
    // description: 'Writing docs.',
    release: false,
  },
  {
    // type: 'deploy',
    emoji: ':rocket:',
    // description: 'Deploying stuff.',
    release: PATCH,
  },
  {
    // type: 'ui',
    emoji: ':lipstick:',
    // description: 'Updating the UI and style files.',
    release: PATCH,
  },
  {
    // type: 'init',
    emoji: ':tada:',
    // description: 'Initial commit.',
    release: PATCH,
  },
  {
    // type: 'test',
    emoji: ':white_check_mark:',
    // description: 'Adding tests.',
    release: false,
  },
  {
    // type: 'security',
    emoji: ':lock:',
    // description: 'Fixing security issues.',
    release: MINOR,
  },
  {
    // type: 'osx',
    emoji: ':apple:',
    // description: 'Fixing something on macOS.',
    release: PATCH,
  },
  {
    // type: 'linux',
    emoji: ':penguin:',
    // description: 'Fixing something on Linux.',
    release: PATCH,
  },
  {
    // type: 'windows',
    emoji: ':checkered_flag:',
    // description: 'Fixing something on Windows.',
    release: PATCH,
  },
  {
    // type: 'android',
    emoji: ':robot:',
    // description: 'Fixing something on Android.',
    release: PATCH,
  },
  {
    // type: 'ios',
    emoji: ':green_apple:',
    // description: 'Fixing something on iOS.',
    release: PATCH,
  },
  {
    // type: 'release',
    emoji: ':bookmark:',
    // description: 'Releasing / Version tags.',
    release: PATCH,
  },
  {
    // type: 'lint',
    emoji: ':rotating_light:',
    // description: 'Removing linter warnings.',
    release: PATCH,
  },
  {
    // type: 'wip',
    emoji: ':construction:',
    // description: 'Work in progress.',
    release: false, // don't create a release
  },
  {
    // type: 'fix-ci',
    emoji: ':green_heart:',
    // description: 'Fixing CI Build.',
    release: PATCH,
  },
  {
    // type: 'downgrade',
    emoji: ':arrow_down:',
    // description: ' Downgrading dependencies.',
    release: PATCH,
  },
  {
    // type: 'upgrade',
    emoji: ':arrow_up:',
    // description: ' Upgrading dependencies.',
    release: PATCH,
  },
  {
    // type: 'pushpin',
    emoji: ':pushpin:',
    // description: 'Pinning dependencies to specific versions.',
    release: false,
  },
  {
    // type: 'ci',
    emoji: ':construction_worker:',
    // description: 'Adding CI build system.',
    release: PATCH,
  },
  {
    // type: 'analytics',
    emoji: ':chart_with_upwards_trend:',
    // description: 'Adding analytics or tracking code.',
    release: PATCH,
  },
  {
    // type: 'refactoring',
    emoji: ':recycle:',
    // description: ' Refactoring code.',
    release: MINOR,
  },
  {
    // type: 'docker',
    emoji: ':whale:',
    // description: 'Work about Docker.',
    release: PATCH,
  },
  {
    // type: 'dep-add',
    emoji: ':heavy_plus_sign:',
    // description: 'Adding a dependency.',
    release: PATCH,
  },
  {
    // type: 'dep-rm',
    emoji: ':heavy_minus_sign:',
    // description: 'Removing a dependency.',
    release: PATCH,
  },
  {
    // type: 'config',
    emoji: ':wrench:',
    // description: 'Changing configuration files.',
    release: PATCH,
  },
  {
    // type: 'i18n',
    emoji: ':globe_with_meridians:',
    // description: 'Internationalization and localization.',
    release: PATCH,
  },
  {
    // type: 'typo',
    emoji: ':pencil2:',
    // description: ' Fixing typos.',
    release: PATCH,
  },
  {
    // type: 'poo',
    emoji: ':poop:',
    // description: 'Writing bad code that needs to be improved.',
    release: PATCH,
  },
  {
    // type: 'revert',
    emoji: ':rewind:',
    // description: 'Reverting changes.',
    release: PATCH,
  },
  {
    // type: 'merge',
    emoji: ':twisted_rightwards_arrows:',
    // description: 'Merging branches.',
    release: PATCH,
  },
  {
    // type: 'dep-up',
    emoji: ':package:',
    // description: 'Updating compiled files or packages.',
    release: PATCH,
  },
  {
    // type: 'compat',
    emoji: ':alien:',
    // description: 'Updating code due to external API changes.',
    release: PATCH,
  },
  {
    // type: 'mv',
    emoji: ':truck:',
    // description: 'Moving or renaming files.',
    release: PATCH,
  },
  {
    // type: 'license',
    emoji: ':page_facing_up:',
    // description: 'Adding or updating license.',
    release: false,
  },
  {
    // type: 'breaking',
    emoji: ':boom:',
    // description: 'Introducing breaking changes.',
    release: MAJOR,
  },
  {
    // type: 'assets',
    emoji: ':bento:',
    // description: 'Adding or updating assets.',
    release: PATCH,
  },
  {
    // type: 'review',
    emoji: ':ok_hand:',
    // description: 'Updating code due to code review changes.',
    release: PATCH,
  },
  {
    // type: 'access',
    emoji: ':wheelchair:',
    // description: 'Improving accessibility.',
    release: PATCH,
  },
  {
    // type: 'docs-code',
    emoji: ':bulb:',
    // description: 'Documenting source code.',
    release: PATCH,
  },
  {
    // type: 'beer',
    emoji: ':beers:',
    // description: 'Writing code drunkenly.',
    release: PATCH,
  },
  {
    // type: 'texts',
    emoji: ':speech_balloon:',
    // description: 'Updating text and literals.',
    release: PATCH,
  },
  {
    // type: 'db',
    emoji: ':card_file_box:',
    // description: ' Performing database related changes.',
    release: PATCH,
  },
  {
    // type: 'log-add',
    emoji: ':loud_sound:',
    // description: 'Adding logs.',
    release: false,
  },
  {
    // type: 'log-rm',
    emoji: ':mute:',
    // description: 'Removing logs.',
    release: false,
  },
  {
    // type: 'contrib-add',
    emoji: ':busts_in_silhouette:',
    // description: 'Adding contributor(s).',
    release: false,
  },
  {
    // type: 'ux',
    emoji: ':children_crossing:',
    // description: 'Improving user experience / usability.',
    release: PATCH,
  },
  {
    // type: 'arch',
    emoji: ':building_construction:',
    // description: ' Making architectural changes.',
    release: PATCH,
  },
  {
    // type: 'iphone',
    emoji: ':iphone:',
    // description: 'Working on responsive design.',
    release: PATCH,
  },
  {
    // type: 'clown-face',
    emoji: ':clown_face:',
    // description: 'Mocking things.',
    release: false,
  },
  {
    // type: 'egg',
    emoji: ':egg:',
    // description: 'Adding an easter egg.',
    release: PATCH,
  },
  {
    // type: 'see-no-evil',
    emoji: ':see_no_evil:',
    // description: 'Adding or updating a .gitignore file',
    release: false,
  },
  {
    // type: 'camera-flash',
    emoji: ':camera_flash:',
    // description: 'Adding or updating snapshots',
    release: false,
  },
  {
    // type: 'experiment',
    emoji: ':alembic:',
    // description: ' Experimenting new things',
    release: false,
  },
  {
    // type: 'seo',
    emoji: ':mag:',
    // description: 'Improving SEO',
    release: PATCH,
  },
  {
    // type: 'k8s',
    emoji: ':wheel_of_dharma:',
    // description: ' Work about Kubernetes',
    release: PATCH,
  },
  {
    // type: 'types',
    emoji: ':label:',
    // description: ' Adding or updating types (Flow, TypeScript)',
    release: PATCH,
  },
  {
    // type: 'seed',
    emoji: ':seedling:',
    // description: 'Adding or updating seed files',
    release: PATCH,
  },
  {
    // type: 'flags',
    emoji: ':triangular_flag_on_post:',
    // description: 'Adding, updating, or removing feature flags',
    release: PATCH,
  },
  {
    // type: 'animation',
    emoji: ':dizzy:',
    // description: 'Adding or updating animations and transitions',
    release: PATCH,
  },
];


